### ISSUE TITLE
Security fix for 32-bits systems

### ISSUE THREAD

**Issue by Cyan4973** [mwotton/lz4hs#11]
Hi Mark

There is a new security fix for 32-bits system available at : 
https://github.com/Cyan4973/lz4/releases/latest

The issue affects programs accepting very large data blocks in 32-bits mode.

As a security measure, all binders are invited to upgrade their underlying C source code to latest version.

Regards

**Comment by mwotton** [comment]
thanks, released as 0.2.3.1.

**Comment by Cyan4973** [comment]
Great !
Also, as a minor comment : 

If you believe your binder can be used in the context of receiving data from some external source, please prefer using LZ4_decompress_safe() as a decoding function.
It has a slightly different prototype, 
but ensures protection against intentionally malformed data blocks.
