### ISSUE TITLE
How can compression 'fail'?

### ISSUE THREAD

**Issue by christian-marie** [mwotton/lz4hs#9]
I'm a little confused as to the failure case in compression.

Should I be expecting it to fail? What am I meant to do if it does? It'd be nice to document that.

**Comment by mwotton** [comment]
Had a quick look through the code - it looks like it just passes it through from the underlying C library. I don't _think_ it can fail, but if the C copmpression routine passes back an empty string, the Haskell will return Nothing. I don't know the C well enough to know whether that's actually a possible error case.

**Comment by Cyan4973** [comment]
The C source code has little reasons to output an error code.
The first one is : is the input > LZ4_MAX_INPUT_SIZE ?
with LZ4_MAX_INPUT_SIZE being more than 2 billions bytes, so it is expected to never really happen.

The second reason depends on the C function called : 
While LZ4_compress() should never fail, LZ4_compress_limitedOutput() is expected to fail if it cannot match a specified limit regarding output buffer. This can be used to force the compressor to deliver a minimum compression ratio, or to match some strict memory allocation limit.

Obviously, if you don't specify an output buffer size, then only the first function apply.
